### ISSUE TITLE
parallelizzazione-business logic 

### ISSUE THREAD

**Issue by emanuele-depaoli-sdg** [SDGGroup/ecap11s6#6]

**Comment by anna-longari-sdg** [comment]
branch iss05 inserita l parallelizzazione con makeCluster e parLapply (del pacchetto parallel) e portata al livello di do_bl.
- All'inizio vengono aperti i cluster 
- su curve_1y viene creata la variabile ID_SCEN_CLASS come ntile della concatenzione di ID_YEAR, COD_VALUTA, ID_SCEN
- le funzioni do_interpolazione_spline, do_selezione_scenario_shock e do_delta_pv vengono chiamate con parLapply sulla lista dei dati affettati per ID_SCEN_CLASS

**Comment by anna-longari-sdg** [comment]
Pending
- sistemare header roxygen
- testare sui dati completi
- sistemare i test con i parametri modificati
- rifare i test con una selezione più piccola di dati in modo che non si debba farli girare in parallelo

**Comment by anna-longari-sdg** [comment]
ID_SCEN_CLASS studiare un'alternativa a ntile che non funziona con numero di righe non multiplo di n

**Comment by anna-longari-sdg** [comment]
Chiudiamo l'issue 05 mentre ISP sta facendo i test di coerenza

**Comment by anna-longari-sdg** [comment]
Chiudiamo l'issue 05 mentre ISP sta facendo i test di coerenza
